(ns ta.tradingview.chartmaker
  (:require
   [nano-id.core :refer [nano-id]]
   [ta.tradingview.db :refer [save-chart now-epoch chart-list load-chart load-chart-boxed]]
   [ta.tradingview.template.chart :refer [empty-meta empty-chart empty-pane]]
   [ta.tradingview.template.mainseries :refer [mainseries]]
   [ta.tradingview.template.study :refer [study]]
   [ta.tradingview.template.sessions :refer [sessions]]
   [ta.tradingview.template.trendline :as tl ]
   [ta.tradingview.template.pitchfork :as pf ]
   [ta.tradingview.template.gann :as g]))

(def trendline tl/trendline)
(def pitchfork pf/pitchfork)
(def gann g/gann)
(def gann-vertical g/gann-vertical)

(defn make-chart [chart-id symbol name drawings]
  (->> (assoc empty-meta
              :symbol symbol
              :short_name symbol
              :name name
              :desciption "autogenerated desc"
              :charts
              [(assoc
                empty-chart
                :panes [(assoc empty-pane
                               :sources (into [] (concat [mainseries
                                                          study
                                                          sessions]
                                                         drawings)))])])
       (save-chart 77 77 chart-id)))



(comment


  (gann-vertical 1000.0 200.0 5 1511879400 1515076200)

  (->> (assoc empty-meta
              :symbol "AMZN"
              :short_name "AMZN"
              :name "autogen gann2"
              :desciption "autogenerated desc"
              :charts
              [(assoc
                empty-chart
                :panes [(assoc empty-pane
                               :sources [mainseries
                                         study
                                         sessions
                                         (trendline {:symbol "NYSE:APA"
                                                            :a-p 40.20  :a-t 1519223400
                                                            :b-p 35.88060448358687  :b-t 1521725400})
                                         (gann
                                          {:symbol "NasdaqNM:AMZN"
                                           :a-p 1517.0  :a-t 1511879400
                                           :b-p 1794.0  :b-t 1515076200})
                                         ;source-pitchfork
                                         ])])])

       (save-chart 77 77 999))

  (chart-list 10 10)
  (chart-list 77 77)


  (load-chart 77 77 888)

  (load-chart-boxed 77 77 888)

  (-> (load-chart 77 77 722072) ; AMZN: Pitchfork   MSFT: LineTrend
      :charts
      first
      keys)



  (-> (load-chart 77 77 1636558275) ; AMZN: Pitchfork   MSFT: LineTrend
      :content  ; :layout :charts
      :charts
      first
      :panes
      first ; (:sources :leftAxisSources  :rightAxisSources :leftAxisState :rightAxisState  :overlayPriceScales :mainSourceId)
   ; :sources
      :sources
    ;count
      (get 5)
    ;:type
    ;(get-in [:state :styles])
      )

;
  )
