; generated by goldly on 2021-06-14 06:00:32
(ns goldly-bindings-generated
  (:require [pinkgorilla.repl.goldly.core]
            [pinkie.default-setup]
            [ui.site.goldly.core]
            [ui.code.goldly.core]
            [clojure.walk]
            [pinkgorilla.vega.pinkie]
            [pinkgorilla.vega]
            [pinkgorilla.vega.plot.core]
            [pinkgorilla.vega.plot.swings]
            [pinkgorilla.grid]))
(def bindings-generated
  {'clipboard-set pinkgorilla.repl.clipboard/clipboard-set,
   'interval pinkgorilla.repl.cljs.js/interval,
   'sin pinkgorilla.repl.cljs.js/sin,
   'parse-float pinkgorilla.repl.cljs.js/parse-float,
   'println println,
   'text pinkie.text/text,
   'get-edn pinkgorilla.repl.cljs.http/get-edn,
   'clipboard-pop pinkgorilla.repl.clipboard/clipboard-pop,
   'get-str pinkgorilla.repl.cljs.http/get-str,
   'vegalite pinkgorilla.vega/vegalite,
   'pinkie-render pinkie.pinkie-render/pinkie-render,
   'vega pinkgorilla.vega/vega,
   'error pinkgorilla.repl.cljs.log/error,
   'get-json pinkgorilla.repl.cljs.http/get-json,
   'info pinkgorilla.repl.cljs.log/info,
   'evt-val pinkgorilla.repl.cljs.js/evt-val,
   'timeout pinkgorilla.repl.cljs.js/timeout,
   'grid pinkgorilla.grid/grid,
   'warn pinkgorilla.repl.cljs.log/warn,
   'nav pinkgorilla.repl.cljs.webly/nav,
   'dialog pinkgorilla.repl.cljs.webly/dialog,
   'alert pinkgorilla.repl.cljs.js/alert,
   'set-system-state pinkgorilla.repl.cljs.goldly/set-system-state,
   'notify pinkgorilla.repl.cljs.webly/notify})
(def ns-generated
  {'walk {'postwalk clojure.walk/postwalk,
          'prewalk clojure.walk/prewalk,
          'keywordize-keys clojure.walk/keywordize-keys,
          'walk clojure.walk/walk,
          'postwalk-replace clojure.walk/postwalk-replace,
          'prewalk-replace clojure.walk/prewalk-replace,
          'stringify-keys clojure.walk/stringify-keys},
   'plot {'list-plot pinkgorilla.vega.plot.core/list-plot,
          'bar-chart pinkgorilla.vega.plot.core/bar-chart,
          'histogram pinkgorilla.vega.plot.core/histogram,
          'plot pinkgorilla.vega.plot.core/plot,
          'compose pinkgorilla.vega.plot.core/compose,
          'timeseries-plot pinkgorilla.vega.plot.core/timeseries-plot,
          'multi-plot pinkgorilla.vega.plot.core/multi-plot,
          'swing-chart pinkgorilla.vega.plot.swings/swing-chart}})
