name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    # - name: Install dependencies
    #  run: |
    #    lein deps
    - name: clj-fmt
      run: clojure -M:cljfmt
    - name: clj-kondo
      run: clojure -M:lint
    - name: test-clj
      run: |
        clojure -M:test-clj
    - name: cloverage
      run: clojure -M:cloverage
    - name: Release
      if: success()
      # if: github.event_name == 'push'
      env:
        CLOJARS_USERNAME: ${{ secrets.ReleaseUsername }}
        CLOJARS_PASSWORD: ${{ secrets.ReleasePassword }}
        CODECOV_TOKEN: ${{ secrets.CodecovToken }}
      run: |
        git config --global user.email "ci@pinkgorilla.org"
        git config --global user.name "CI/CD"
        clojure -M:release
      # lein release
      # bash <(curl -s https://codecov.io/bash)